# Generated by Django 5.1.5 on 2025-02-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='mcatg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.main_cat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main_cat',
            name='m_name',
            field=models.TextField(unique=True),
        ),
    ]
