# Generated by Django 5.1.5 on 2025-02-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plants_mcatg_alter_main_cat_m_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
