# Generated by Django 5.1.5 on 2025-02-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plants_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
